import {
  BatchCreated,
  BatchUpdated,
  TemperatureExceeded,
} from "../generated/DrugBatch/DrugBatch"; // Import event types generated by The Graph
import { Batch, TemperatureEvent } from "../generated/schema"; // Import entity types generated by The Graph

// Handler function for the BatchCreated event
export function handleBatchCreated(event: BatchCreated): void {
  let batch = new Batch(event.params.id.toString());
  batch.manufacturer = event.params.manufacturer;
  batch.manufactureDate = event.params.manufactureDate;
  batch.expiryDate = event.params.expiryDate;
  batch.status = "Created";
  batch.save();
}

// Handler function for the BatchUpdated event
export function handleBatchUpdated(event: BatchUpdated): void {
  let batch = Batch.load(event.params.id.toString());
  if (batch == null) {
    return;
  }
  batch.status = event.params.status;
  batch.save();
}

// Handler function for the TemperatureExceeded event
export function handleTemperatureExceeded(event: TemperatureExceeded): void {
  let temperatureEvent = new TemperatureEvent(event.transaction.hash.toHex());
  temperatureEvent.batchId = event.params.id.toString();
  temperatureEvent.temperature = event.params.temperature;
  temperatureEvent.timestamp = event.block.timestamp;
  temperatureEvent.save();
}
